title: Youvect
description: Our strategy. Your Success. Marketing redefined.
baseurl: "/website"
url: "https://youvect.github.io"

plugins:
  - jekyll-redirect-from

redirect_from:
  json: false

exclude:
  - README.md
