title: Youvect
description: Our strategy. Your success. Marketing redefined.
baseurl: "/website"
url: "https://youvect.github.io"
language: en
region: gb
twitter: "youvect"

defaults:
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-redirect-from

redirect_from:
  json: false

exclude:
  - README.md

sass:
  style: :compressed
