- title: Social Media Marketing
  description: Promoting your business through platforms like Facebook, Instagram, and Twitter to reach and engage with customers, boost brand awareness, and drive sales.
  icon: user
- title: Search Engine Optimisation
  description: Optimising your website to rank higher in search engine results, increasing visibility and attracting more organic traffic.
  icon: search
- title: Email Marketing
  description: Sending targeted emails to your subscribers to nurture relationships, promote products or services, and drive conversions.
  icon: email
